---
- name: Install and configure web server
  hosts: all
  become: yes
  tasks:
  - name: install nginx
    dnf:
      name: nginx
      state: present
  - name: Copy sample index.html from github
    get_url:
      url: https://raw.githubusercontent.com/ikhan2010/fedora/main/server_info.j2
      dest: /usr/share/nginx/html/index.html
#      dest: server_info.j2
#      owner: root
      group: nginx
#      mode: 0755
#  - name: Render and copy HTML template
#    template:
#      src: server_info.j2
#      dest: /usr/share/nginx/html/index.html
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes
  - name: configure new vlan on a Cisco IOS device
    cisco.ios.ios_vlans:
      config:
        - name: HR_VLAN
          vlan_id: 5
          state: active
          shutdown: disabled
        - name: Sales_VLAN
          vlan_id: 10
          mtu: 1000
          state: active
          shutdown: disabled
        - name: PROC_VLAN
          vlan_id: 30
          state: suspend
          shutdown: enabled
      state: overridden
    register: cisco_output
  



  
   
  

  
