---
- name: Install and configure web server
  hosts: all
  become: yes
  tasks:
  - name: Install Apache web server
    dnf:
      name: httpd
      state: present

  - name: Start Apache web server
    service:
      name: httpd
      state: started

  - name: Update home page
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: 0644
