---
- name: Install and configure web server
  hosts: all
  become: yes
  tasks:
  - name: install nginx
    dnf:
      name: nginx
      state: present
  - name: copy index.html
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
      owner: nginx
      group: nginx
      mode: 0644
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes
